### ISSUE TITLE
【idea】优化和增强API

### ISSUE THREAD

**Issue by hans000** [Jcanno/ajax-fake#4]
先把api定一下，实现应该不太复杂

- force 选项的实际使用场景是什么？不想明白
- 更友好的api支持，onRequestMatch 当返回 undefined 时默认就是 { match: false }; 现在的功能返回 {} 和 { match: false } 应该是等效的吧；更进一步的，其实match可以不要吧？
- 增强功能，现在没有对真实xhr的拦截功能，我看关键字有intercept，是否考虑增加拦截器选项
- 考虑使用 context function api 更加方便

```
fake({
  // 过滤请求，匹配成功会进入handle做进一步处理，返回false，发送真实请求
  filter() {
    return mockData.some(...)
  },
  // 做进一步处理，req类型{ requestUrl: string; method: string } , res类型mock数据, 上面匹配的数据
  handle(req, res) {
    return {
      status: ,
      delay: ,
      response: ,
    }
  },
  // 发送真实请求时，用于拦截请求做修改，参考ajax-hook，这个库似乎不维护了 https://github.com/wendux/Ajax-hook/blob/master/src/xhr-hook.js
  interceptors: {
    // 方法
    onreadstatechange(xhr, ...args /* 原有的参数 */) {
      // 考虑把this指向xhr还是通过形参xhr？
      this.responseText = '1234'
    },
    // 属性
    responseText: {
      getter(v, xhr) {
        return update(v)
      },
      setter(value, xhr) {

      }
    }
  },
})
```

**Comment by Jcanno** [comment]
- force为false时只是简单的xhr对象替换，为true时通过修改window上数据元信息防止被其他代码修改，应用场景是如果是简单替换的话会与其他修改xhr的代码/库会形成冲突，造成fake失效(这个要看代码执行的顺序，如果ajax-fake在其他库后面执行，则还是会生效)
- 这个可以按你的做修改
- 3、4可以考虑下哈，上下文对象是可以封装的，目前功能还是偏向修改响应数据多一些(偏于mock)

**Comment by hans000** [comment]
> * force为false时只是简单的xhr对象替换，为true时通过修改window上数据元信息防止被其他代码修改，应用场景是如果是简单替换的话会与其他修改xhr的代码/库会形成冲突，造成fake失效(这个要看代码执行的顺序，如果ajax-fake在其他库后面执行，则还是会生效)
> * 这个可以按你的做修改
> * 3、4可以考虑下哈，上下文对象是可以封装的，目前功能还是偏向修改响应数据多一些(偏于mock)

主要我的个人项目easy-interceptor遇到些麻烦，同时用两个库会有冲突，并且ajax-hook有缺陷，也不维护了，所以考虑集成在这个库里，api还在考虑怎么好用，看具体实现吧

**Comment by hans000** [comment]
调整了api，现在是这个样式的，我那边基本完成了功能，并且更改了一些配置，更改点有

- 把输出的文件统一到dist目录下
- 添加了生成iife的配置
- 简单拆分了一下目录
- tsconfig 启用了严格模式
- 添加了部分测试用例
- 更新了中文readme
- （还有啥，想不起来了，可以先review一下）

```
fake({
    force: false,
    onMatch(req) {
    },
    onHandle(data) {
    },
    onIntercept(data) {
    },

})


```

**Comment by hans000** [comment]
调整了api，现在是这个样式的，我那边基本完成了功能，并且更改了一些配置，更改点有

- 把输出的文件统一到dist目录下
- 添加了生成iife的配置
- 简单拆分了一下目录
- tsconfig 启用了严格模式
- 添加了部分测试用例
- 更新了中文readme
- （还有啥，想不起来了，可以先review一下）

```
fake({
    force: false,
    onMatch(req) {
    },
    onHandle(data) {
    },
    onIntercept(data) {
    },

})


```
